// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Users)(nil), "user.Users")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8e, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xb7, 0xab, 0xeb, 0x14, 0x3d, 0x0c, 0x28, 0xa1, 0x5e, 0xc2, 0x9e, 0xea, 0x25,
	0x81, 0xf5, 0x15, 0x14, 0xef, 0x2d, 0x3e, 0x40, 0x6b, 0xc6, 0x52, 0xb0, 0x4d, 0x49, 0xda, 0x82,
	0x6f, 0x2f, 0x99, 0x50, 0xf4, 0xe2, 0x25, 0xcc, 0x37, 0x93, 0xf9, 0xe7, 0x83, 0xfb, 0xd9, 0xbb,
	0xc5, 0x99, 0x35, 0x90, 0xe7, 0x47, 0x33, 0x63, 0x1e, 0xeb, 0xf2, 0xb1, 0x77, 0xae, 0xff, 0x22,
	0xc3, 0xbd, 0x6e, 0xfd, 0x34, 0x34, 0xce, 0xcb, 0x77, 0xfa, 0x72, 0x7e, 0x81, 0xfc, 0x3d, 0x90,
	0xc7, 0x3b, 0xc8, 0x06, 0x2b, 0x85, 0x12, 0xd5, 0x6d, 0x9d, 0x0d, 0x16, 0x11, 0xf2, 0xa9, 0x1d,
	0x49, 0x66, 0x4a, 0x54, 0x37, 0x35, 0xd7, 0x28, 0xe1, 0xba, 0xb5, 0xd6, 0x53, 0x08, 0xf2, 0xc0,
	0xed, 0x1d, 0xcf, 0x4f, 0x70, 0x8c, 0x29, 0x01, 0x15, 0x1c, 0xe3, 0xcd, 0x20, 0x85, 0x3a, 0x54,
	0xc5, 0x05, 0x34, 0xdb, 0xc4, 0x59, 0x9d, 0x06, 0x97, 0x09, 0x8a, 0x88, 0x0d, 0xf9, 0x6d, 0xf8,
	0x20, 0x34, 0x70, 0x7a, 0xa3, 0x25, 0x2d, 0x3f, 0xe8, 0x64, 0xaa, 0x77, 0x53, 0xfd, 0x1a, 0x4d,
	0xcb, 0xe2, 0x37, 0x25, 0xa0, 0x86, 0x53, 0xd3, 0x6e, 0xc4, 0xd2, 0x7f, 0xe2, 0xcb, 0x7f, 0x96,
	0xbb, 0x2b, 0xe6, 0xe7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x85, 0x59, 0xfd, 0x8b, 0x23, 0x01,
	0x00, 0x00,
}
